<?php
// Automatically Generated by TestLink Installer - Wed, 10 Jan 18 05:44:18 +0100
define('DB_TYPE', 'mysql');
define('DB_USER', 'tharaka');
define('DB_PASS', 'tharaka123');
define('DB_HOST', '192.168.1.183');
define('DB_NAME', 'testlink_new');
define('DB_TABLE_PREFIX', '');
