<?php
// Automatically Generated by TestLink Installer - Wed, 06 Dec 17 07:39:51 +0100
define('DB_TYPE', 'mysql');
define('DB_USER', 'admin');
define('DB_PASS', 'admin');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
