<?php
// Automatically Generated by TestLink Installer - Wed, 29 Mar 17 12:07:53 +0200
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink\User');
define('DB_PASS', '1qaz2wsx@');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
